server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.73.131
aliyun:
  sms:
    accessKeyId: LTAIUDaFoVRKL2xX
    accessKeySecret: CtWPuthfaz9uaqT4wR0aok0dUEHRhk
    template_code: SMS_171188373
    sign_name: 十次方square